---

- name: Deploy fluffy plushies on faramir
  hosts: faramir-host
  become: True
  remote_user: fluffy_ansible
  tags: [ 'faramir-host', 'fluffy', 'plushies', 'deploy' ]
  tasks: [ ]
  roles:
    - {role: docker}
#    - {role: user,
#       user_name: fluffy,
#       user_default_groups: [ "users", "docker" ],
#       user_password: "{{ vault_faramir_host_angmar_password_hash }}",
#       tags: [ "users" ]
#    }
   # checkout repository as fluffy
  # run docker compose as fluffy



  # configure firewall

