---

- name: Deploy fluffy plushies on faramir
  hosts: faramir-host
  become: True
  remote_user: fluffy_ansible
  tags: [ 'faramir-host', 'fluffy', 'plushies', 'deploy' ]
  vars: {}
  tasks: []
  roles:
    - {role: docker}
    - {role: user,
       user_name: fluffy,
       user_default_groups: [ "fluffy", "users", "docker" ],
       user_password: "{{ vault_faramir_host_fluffy_password_hash }}",
       tags: [ "users" ]
    }
    - { role: firewall, tags: ['ufw', 'firewall']}
    - { role: deploy_from_github, tags: [ 'deploy', 'git', 'docker' ] }

