# This will install and configure a basic ufw firewall
# ansible_become: yes

- name: Install ufw
  apt: pkg=ufw state=present update_cache=yes
  become: yes
  tags: ufw

- name: Enable ufw
  ufw:
    state: enabled
    policy: allow
  notify: reload ufw

- name: enable ufw logging
  ufw:
    logging: on
  notify: reload ufw

- name: configure ufw logging level
  ufw:
    logging: "{{ ufw_logging }}"
  notify: reload ufw

- name: ufw allow IPv4 forwarding between interfaces
  lineinfile:
    dest: /etc/ufw/sysctl.conf
    line: net/ipv4/ip_forward=1
    regexp: "#net/ipv4/ip_forward\\="

- name: ufw allow IPv6 forwarding between interfaces
  lineinfile:
    dest: /etc/ufw/sysctl.conf
    line: net/ipv6/conf/default/forwarding=1
    regexp: "#net/ipv6/conf/default/forwarding\\="

- name: ufw allow IPv6 forwarding for all interfaces
  lineinfile:
    dest: /etc/ufw/sysctl.conf
    line: net/ipv6/conf/all/forwarding=1
    regexp: "#net/ipv6/conf/all/forwarding\\="

- name: rules
  ufw:
    rule: "{{ item.rule }}"
    interface: "{{ item.interface | default('') }}"
    direction: "{{ item.direction | default('in') }}"
    from_ip: "{{ item.from_ip | default('any') }}"
    to_ip: "{{ item.to_ip | default('any') }}"
    from_port: "{{ item.from_port | default('') }}"
    to_port: "{{ item.to_port | default('') }}"
    protocol: "{{ item.protocol | default('any') }}"
    log: "{{ item.log | default(False) }}"
  with_items: "{{ ufw_rules }}"
  notify: reload ufw