# This will install and configure a basic ufw firewall
# ansible_become: yes

- name: Install ufw
  apt: pkg=ufw state=present update_cache=yes
  become: yes
  tags: ufw

- name: Enable ufw
  ufw:
    state: enabled
    policy: allow
  notify: reload ufw

- name: enable ufw logging
  ufw:
    logging: on
  notify: reload ufw

- name: configure ufw logging level
  ufw:
    logging: "{{ ufw_logging }}"
  notify: reload ufw

- name: Set default incoming policy
  ufw:
    default: "{{ ufw_default_incoming_policy }}"
    direction: incoming
  notify: reload ufw

- name: Set default outgoing policy
  ufw:
    default: "{{ ufw_default_outgoing_policy }}"
    direction: outgoing
  notify: reload ufw

- name: Set default routed policy
  ufw:
    default: "{{ ufw_default_routed_policy }}"
    direction: routed
  notify: reload ufw

- name: rules
  ufw:
    rule: "{{ item.rule }}"
    interface: "{{ item.interface | default('') }}"
    direction: "{{ item.direction | default('in') }}"
    from_ip: "{{ item.from_ip | default('any') }}"
    to_ip: "{{ item.to_ip | default('any') }}"
    from_port: "{{ item.from_port | default('') }}"
    to_port: "{{ item.to_port | default('') }}"
    protocol: "{{ item.protocol | default('any') }}"
    log: "{{ item.log | default(False) }}"
    comment: "{{ item.comment | default(omit) }}"
  with_items: "{{ ufw_rules }}"
  notify: reload ufw