name: Identity Service

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/identity-service.yml'
      - 'IdentityService/**'
  pull_request:
    paths:
      - '.github/workflows/identity-service.yml'
      - 'IdentityService/**'
  workflow_dispatch:

env:
  DOCKER_REPO: ghcr.io/websecdetectives
  IMAGE_NAME: fluffy-plushies-identity:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.XGITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./IdentityService
          file: ./IdentityService/Dockerfile
          push: false
          tags: ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
