name: Identity Service

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/identity-service.yml'
      - 'IdentityService/**'
  pull_request:
    paths:
      - '.github/workflows/identity-service.yml'
      - 'IdentityService/**'
  workflow_dispatch:

env:
  DOCKER_REPO: ghcr.io/websecdetectives
  IMAGE_NAME: fluffy-plushies-identity:latest

permissions:
  contents: read
  security-events: write
  packages: write

jobs:
  build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    outputs:
      image-ref: ${{ steps.build.outputs.image-ref }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./IdentityService
          file: ./IdentityService/Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
      - id: build
        run: |
          echo "image-ref=${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build Identity Service
        working-directory: IdentityService
        run: mvn clean package -DskipTests -B

      - name: Build Inventory Service
        working-directory: InventoryService
        run: mvn clean package -DskipTests -B

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

  checkov:
    name: Checkov Ansible Scan
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Checkov
        run: pip install checkov
      - name: Run Checkov
        run: checkov --framework ansible -d ansible/

  trivy:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull built image
        run: docker pull ${{ needs.build.outputs.image-ref }}

      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          image-ref: ${{ needs.build.outputs.image-ref }}

  zap:
    name: OWASP ZAP DAST
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull built image
        run: docker pull ${{ needs.build.outputs.image-ref }}

      - name: Start container
        run: docker run -d --name web -p 8081:8081 ${{ needs.build.outputs.image-ref }}

      - name: Wait for web service
        run: |
          for i in $(seq 1 30); do
            nc -z localhost 8081 && break
            sleep 1
          done
      - name: Start ZAP baseline scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://host.docker.internal:8081'