name: Security Scans

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/security-scans.yml'
      - 'IdentityService/**'
      - 'InventoryService/**'
      - 'ansible/**'
  pull_request:
    paths:
      - '.github/workflows/security-scans.yml'
      - 'IdentityService/**'
      - 'InventoryService/**'
      - 'ansible/**'
  workflow_dispatch:

env:
  DOCKER_REPO: ghcr.io/websecdetectives
  IMAGE_NAME: fluffy-plushies-identity:latest

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build Identity Service
        working-directory: IdentityService
        run: mvn clean package -DskipTests -B

      - name: Build Inventory Service
        working-directory: InventoryService
        run: mvn clean package -DskipTests -B

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: codeql
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          token: ${{ secrets.XGITHUB_TOKEN }}

  trivy:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: dependency-review
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_REPO/$IMAGE_NAME IdentityService/
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: image
          image-ref: $DOCKER_REPO/$IMAGE_NAME

  checkov:
    name: Checkov Ansible Scan
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: trivy
    steps:
      - uses: actions/checkout@v4
      - name: Install Checkov
        run: pip install checkov
      - name: Run Checkov
        run: checkov --framework ansible -d ansible/

  zap:

    name: OWASP ZAP DAST
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: trivy
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.XGITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./IdentityService
          file: ./IdentityService/Dockerfile
          push: false
          tags: ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
      - name: Start container
        run: docker run -d --name web -p 8081:8081 ${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}

      - name: Wait for web service
        run: |
          for i in $(seq 1 30); do
            nc -z localhost 8081 && break
            sleep 1
          done
      - name: Start ZAP baseline scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://host.docker.internal:8081'